services:
  webapp:
    image: nginxdemos/hello:latest
    container_name: web-test-java
    restart: always
    networks:
      - homelab_network

# El segundo contenedor para probar teoría de que dozzle agrupa por stack cuando hay mas de 1
#  test-probe:
#    image: alpine
#    container_name: probe-stack-apps
#    command: sleep infinity
#    restart: always
#    networks:
#      - homelab_network
      
networks:
  homelab_network:
    external: true
