services:

  # Proxy Inverso: La puerta de entrada
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-proxy/data:/data
      - ./nginx-proxy/letsencrypt:/etc/letsencrypt
    networks:
      - homelab_network

  # DNS y Bloqueo: El cerebro de la red
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'Linux1234'
      FTLCONF_LOCAL_IPV4: '10.0.0.11'
    volumes:
      - ./pihole/config:/etc/pihole
      - ./pihole/dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    networks:
      - homelab_network

  # Logs en vivo
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    networks:
      - homelab_network

  # Orquestador: Gestión de contenedores
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
    networks:
      - homelab_network

networks:
  homelab_network:
    name: homelab_network  # <-- Esto garantiza que el nombre sea exacto para los demás

volumes:
  portainer_data:
    external: true
