#version: '3.8'

services:
  # 1. El Sensor (cAdvisor)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0 # Versión estable
    container_name: cadvisor
    restart: unless-stopped
    privileged: true # <-- Esto es clave en algunas distros de Ubuntu para leer los nombres
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring

  # 2. La Base de Datos (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=5GB'
    networks:
      - monitoring

  # 3. La Interfaz (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # Mapeo de Provisioning (Configuraciones)
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      # Mapeo de la carpeta donde pondrás tus JSON
      - ./grafana/dashboards_json:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring
  
  # 4. node-exporter monitorea hardware de VM. Se agrega para monitorear docker en Dashboard Grafana
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: homelab_network

volumes:
  prometheus_data:
  grafana_data:
